steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/laberu/new-laberu', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/laberu/new-laberu']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'new-laberu',
        '--image',
        'gcr.io/laberu/new-laberu',
        '--region',
        'asia-southeast1-a',
      ]
images:
  - gcr.io/laberu/new-laberu
